"""add images to playgrounds

Revision ID: f31062c48713
Revises: 64510dca643b
Create Date: 2023-07-01 10:20:38.898562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31062c48713'
down_revision = '64510dca643b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playgrounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playgrounds', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
